import { describe, expect, it } from "vitest";

import { COUNTRY_PUBLISH_MIN, MIN_CELL_SIZE } from "./thresholds";
import {
  type Distribution,
  type SiteStats,
  countriesNearingPublication,
  getSiteStats,
  percentileAt,
  publishableCountries,
  totalCount,
} from "./stats";

/** A country row for one population, defaulting to full-time employees. */
function row(
  name: string,
  responses: number,
  over: Partial<SiteStats["countries"][number]> = {},
): SiteStats["countries"][number] {
  return {
    population: "employee",
    code: name.slice(0, 2).toUpperCase(),
    name,
    currency: "EUR",
    responses,
    median: null,
    p25: null,
    p75: null,
    ...over,
  };
}

function statsWith(countries: SiteStats["countries"]): SiteStats {
  return {
    totalResponses: countries.reduce((sum, c) => sum + c.responses, 0),
    countriesCovered: new Set(countries.map((c) => c.code)).size,
    cuts: {},
    countries,
  };
}

/** Flat distribution: 10 bins of 10 across 0–100,000. Easy to reason about. */
const flat: Distribution = {
  n: 100,
  median: 50_000,
  lo: 0,
  hi: 100_000,
  bins: Array.from({ length: 10 }, (_, i) => ({
    lo: i * 10_000,
    hi: (i + 1) * 10_000,
    count: 10,
  })),
};

describe("percentileAt", () => {
  it("puts the midpoint of a flat distribution at the median", () => {
    expect(percentileAt(flat, 50_000)).toBe(50);
  });

  it("interpolates inside a bin rather than snapping to its edge", () => {
    // Half way through the sixth bin: 50 below it, plus half of that bin's 10.
    expect(percentileAt(flat, 55_000)).toBe(55);
  });

  it("clamps to 1 at and below the floor", () => {
    expect(percentileAt(flat, 0)).toBe(1);
    expect(percentileAt(flat, -10_000)).toBe(1);
  });

  it("clamps to 99 at and above the ceiling, never claiming 100", () => {
    expect(percentileAt(flat, 100_000)).toBe(99);
    expect(percentileAt(flat, 10_000_000)).toBe(99);
  });

  it("rises monotonically across the range", () => {
    let previous = 0;
    for (let v = 0; v <= 100_000; v += 2_500) {
      const p = percentileAt(flat, v);
      expect(p).toBeGreaterThanOrEqual(previous);
      previous = p;
    }
  });

  it("returns a floor value for an empty distribution rather than dividing by zero", () => {
    expect(percentileAt({ ...flat, bins: [] }, 50_000)).toBe(1);
  });
});

describe("totalCount", () => {
  it("sums the bins", () => {
    expect(totalCount(flat)).toBe(100);
  });
});

describe("the shipped dataset", () => {
  // These are invariants, not a snapshot of today. An earlier version asserted
  // the file was empty, which would have started failing the day the first
  // real response landed — a test that expires is worse than no test.

  // A previous version searched the file for the design comp's placeholder
  // numbers. That is unsound: €115,000 is a perfectly plausible real median,
  // so the check would have started failing on correct data. The invariants
  // below are the real protection, and the file is now generated by a tested
  // pipeline rather than written by hand.

  it("never publishes a median below the publication threshold", async () => {
    const { countries } = await getSiteStats();
    for (const country of countries) {
      if (country.median !== null) {
        expect(country.responses).toBeGreaterThanOrEqual(COUNTRY_PUBLISH_MIN);
      }
    }
  });

  it("withholds every figure for a country under the threshold", async () => {
    const { countries } = await getSiteStats();
    for (const country of countries) {
      if (country.responses < COUNTRY_PUBLISH_MIN) {
        expect(country.median).toBeNull();
        expect(country.p25).toBeNull();
        expect(country.p75).toBeNull();
      }
    }
  });

  it("leaves no histogram bucket holding an identifiable handful of people", async () => {
    const stats = await getSiteStats();
    for (const cut of Object.values(stats.cuts)) {
      for (const bin of cut.distribution?.bins ?? []) {
        expect(bin.count === 0 || bin.count >= MIN_CELL_SIZE).toBe(true);
      }
    }
  });

  it("keeps the summary counts consistent with the country list", async () => {
    const stats = await getSiteStats();
    // One row per population per country, so the distinct countries covered is
    // never more than the rows and usually fewer.
    expect(stats.countriesCovered).toBe(new Set(stats.countries.map((c) => c.code)).size);
    expect(stats.totalResponses).toBeGreaterThanOrEqual(
      stats.countries.reduce((sum, c) => sum + c.responses, 0),
    );
  });
});

describe("publishableCountries", () => {
  it("keeps only countries at or above their population's threshold", () => {
    const rows = publishableCountries(
      statsWith([
        row("Germany", 60, { median: 70_000 }),
        row("Portugal", 59),
        row("Czechia", 5, { currency: "CZK" }),
      ]),
      "employee",
    );
    expect(rows.map((r) => r.name)).toEqual(["Germany"]);
  });

  it("does not mix one population's rows into another's", () => {
    const stats = statsWith([
      row("Germany", 60, { median: 70_000 }),
      row("Germany", 30, { population: "contractor", median: 650 }),
    ]);
    expect(publishableCountries(stats, "contractor").map((r) => r.median)).toEqual([650]);
  });
});

describe("countriesNearingPublication", () => {
  it("ranks the unpublished countries by how close they are", () => {
    const rows = countriesNearingPublication(
      statsWith([row("Portugal", 12), row("Germany", 47), row("Spain", 30)]),
    );
    expect(rows.map((r) => r.name)).toEqual(["Germany", "Spain", "Portugal"]);
  });

  it("ranks by the share of the threshold reached, not by raw count", () => {
    // 20 contractor day rates is five short of publishing; 20 salaries is
    // forty short. Ranking those by count alone puts the far one first and
    // sends people to the wrong gap.
    const rows = countriesNearingPublication(
      statsWith([
        row("Germany", 25),
        row("Poland", 20, { population: "contractor" }),
      ]),
    );
    expect(rows.map((r) => r.name)).toEqual(["Poland", "Germany"]);
  });

  it("drops countries that have already published", () => {
    // A published country is no longer something a visitor can help with, so
    // listing it would be asking for an answer that changes nothing.
    const rows = countriesNearingPublication(
      statsWith([row("Germany", 60, { median: 70_000 }), row("Spain", 30)]),
    );
    expect(rows.map((r) => r.name)).toEqual(["Spain"]);
  });

  it("returns nothing during the cold start, so the section stays hidden", () => {
    expect(countriesNearingPublication(statsWith([]))).toEqual([]);
  });

  it("breaks ties by name rather than leaving the order to the aggregation", () => {
    const rows = countriesNearingPublication(statsWith([row("Spain", 20), row("Austria", 20)]));
    expect(rows.map((r) => r.name)).toEqual(["Austria", "Spain"]);
  });

  it("caps the list so the page does not turn into a leaderboard of twenty-seven", () => {
    const many = Array.from({ length: 12 }, (_, i) => row(`Country ${i}`, 12 - i));
    expect(countriesNearingPublication(statsWith(many))).toHaveLength(6);
    expect(countriesNearingPublication(statsWith(many), 3)).toHaveLength(3);
  });
});
