import { describe, expect, it } from "vitest";

import { COUNTRY_PUBLISH_MIN, MIN_CELL_SIZE } from "./thresholds";
import {
  type Distribution,
  type SiteStats,
  countriesNearingPublication,
  getSiteStats,
  percentileAt,
  publishableCountries,
  totalCount,
} from "./stats";

/** Flat distribution: 10 bins of 10 across 0–100,000. Easy to reason about. */
const flat: Distribution = {
  n: 100,
  median: 50_000,
  lo: 0,
  hi: 100_000,
  bins: Array.from({ length: 10 }, (_, i) => ({
    lo: i * 10_000,
    hi: (i + 1) * 10_000,
    count: 10,
  })),
};

describe("percentileAt", () => {
  it("puts the midpoint of a flat distribution at the median", () => {
    expect(percentileAt(flat, 50_000)).toBe(50);
  });

  it("interpolates inside a bin rather than snapping to its edge", () => {
    // Half way through the sixth bin: 50 below it, plus half of that bin's 10.
    expect(percentileAt(flat, 55_000)).toBe(55);
  });

  it("clamps to 1 at and below the floor", () => {
    expect(percentileAt(flat, 0)).toBe(1);
    expect(percentileAt(flat, -10_000)).toBe(1);
  });

  it("clamps to 99 at and above the ceiling, never claiming 100", () => {
    expect(percentileAt(flat, 100_000)).toBe(99);
    expect(percentileAt(flat, 10_000_000)).toBe(99);
  });

  it("rises monotonically across the range", () => {
    let previous = 0;
    for (let v = 0; v <= 100_000; v += 2_500) {
      const p = percentileAt(flat, v);
      expect(p).toBeGreaterThanOrEqual(previous);
      previous = p;
    }
  });

  it("returns a floor value for an empty distribution rather than dividing by zero", () => {
    expect(percentileAt({ ...flat, bins: [] }, 50_000)).toBe(1);
  });
});

describe("totalCount", () => {
  it("sums the bins", () => {
    expect(totalCount(flat)).toBe(100);
  });
});

describe("the shipped dataset", () => {
  // These are invariants, not a snapshot of today. An earlier version asserted
  // the file was empty, which would have started failing the day the first
  // real response landed — a test that expires is worse than no test.

  // A previous version searched the file for the design comp's placeholder
  // numbers. That is unsound: €115,000 is a perfectly plausible real median,
  // so the check would have started failing on correct data. The invariants
  // below are the real protection, and the file is now generated by a tested
  // pipeline rather than written by hand.

  it("never publishes a median below the publication threshold", async () => {
    const { countries } = await getSiteStats();
    for (const country of countries) {
      if (country.median !== null) {
        expect(country.responses).toBeGreaterThanOrEqual(COUNTRY_PUBLISH_MIN);
      }
    }
  });

  it("withholds every figure for a country under the threshold", async () => {
    const { countries } = await getSiteStats();
    for (const country of countries) {
      if (country.responses < COUNTRY_PUBLISH_MIN) {
        expect(country.median).toBeNull();
        expect(country.p25).toBeNull();
        expect(country.p75).toBeNull();
      }
    }
  });

  it("leaves no histogram bucket holding an identifiable handful of people", async () => {
    const { europe } = await getSiteStats();
    for (const bin of europe?.bins ?? []) {
      expect(bin.count === 0 || bin.count >= MIN_CELL_SIZE).toBe(true);
    }
  });

  it("keeps the summary counts consistent with the country list", async () => {
    const stats = await getSiteStats();
    expect(stats.countriesCovered).toBe(stats.countries.length);
    expect(stats.totalResponses).toBeGreaterThanOrEqual(
      stats.countries.reduce((sum, c) => sum + c.responses, 0),
    );
  });
});

describe("publishableCountries", () => {
  it("keeps only countries at or above the publication threshold", () => {
    const rows = publishableCountries({
      totalResponses: 100,
      countriesCovered: 3,
      europe: null,
      cuts: {},
      countries: [
        { name: "Germany", currency: "EUR", responses: 60, median: 70_000, p25: null, p75: null },
        { name: "Portugal", currency: "EUR", responses: 59, median: null, p25: null, p75: null },
        { name: "Czechia", currency: "CZK", responses: 5, median: null, p25: null, p75: null },
      ],
    });
    expect(rows.map((r) => r.name)).toEqual(["Germany"]);
  });
});

describe("countriesNearingPublication", () => {
  const statsWith = (countries: SiteStats["countries"]): SiteStats => ({
    totalResponses: countries.reduce((sum, c) => sum + c.responses, 0),
    countriesCovered: countries.length,
    europe: null,
    cuts: {},
    countries,
  });

  const row = (name: string, responses: number, median: number | null = null) => ({
    name,
    currency: "EUR",
    responses,
    median,
    p25: null,
    p75: null,
  });

  it("ranks the unpublished countries by how close they are", () => {
    const rows = countriesNearingPublication(
      statsWith([row("Portugal", 12), row("Germany", 47), row("Spain", 30)]),
    );
    expect(rows.map((r) => r.name)).toEqual(["Germany", "Spain", "Portugal"]);
  });

  it("drops countries that have already published", () => {
    // A published country is no longer something a visitor can help with, so
    // listing it would be asking for an answer that changes nothing.
    const rows = countriesNearingPublication(
      statsWith([row("Germany", 60, 70_000), row("Spain", 30)]),
    );
    expect(rows.map((r) => r.name)).toEqual(["Spain"]);
  });

  it("returns nothing during the cold start, so the section stays hidden", () => {
    expect(countriesNearingPublication(statsWith([]))).toEqual([]);
  });

  it("breaks ties by name rather than leaving the order to the aggregation", () => {
    const rows = countriesNearingPublication(statsWith([row("Spain", 20), row("Austria", 20)]));
    expect(rows.map((r) => r.name)).toEqual(["Austria", "Spain"]);
  });

  it("caps the list so the page does not turn into a leaderboard of twenty-seven", () => {
    const many = Array.from({ length: 12 }, (_, i) => row(`Country ${i}`, 12 - i));
    expect(countriesNearingPublication(statsWith(many))).toHaveLength(6);
    expect(countriesNearingPublication(statsWith(many), 3)).toHaveLength(3);
  });
});
